name: be_positive
description: A personalized affirmations mobile app for daily motivation and positive reinforcement.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Local Database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # Navigation
  go_router: ^14.2.7
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # Utilities
  uuid: ^4.4.2
  intl: ^0.19.0
  timezone: ^0.9.4
  android_intent_plus: ^5.3.0
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/
